---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ .Release.Name }}
rules:
  - apiGroups: [ '' ] # "" indicates the core API group
    resources:
      - namespaces
      - pods
      - nodes
    verbs:
      - get
      - watch
      - list

{{ if .Values.Metricbeat.enabled }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: metricbeat
  labels:
    {{- include "metricbeat.labels" . | indent 4 }}
rules:
  - apiGroups: [ '' ]
    resources:
      - nodes
      - namespaces
      - events
      - pods
      - services
    verbs: [ 'get', 'list', 'watch' ]
  - apiGroups: [ 'extensions' ]
    resources:
      - replicasets
    verbs: [ 'get', 'list', 'watch' ]
  - apiGroups: [ 'apps' ]
    resources:
      - statefulsets
      - deployments
      - replicasets
    verbs: [ 'get', 'list', 'watch' ]
  - apiGroups: [ 'coordination.k8s.io' ]
    resources:
      - leases
    verbs: [ 'create', 'get', 'list', 'update' ]
  - apiGroups: [ 'batch' ]
    resources:
      - jobs
      - cronjobs
    verbs: [ 'get', 'list', 'watch' ]
  - apiGroups:
      - ''
    resources:
      - nodes/stats
    verbs:
      - get
  - nonResourceURLs:
      - '/metrics'
    verbs:
      - get
{{- end -}}