{{ if .Values.Metricbeat.enabled }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metricbeat
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "metricbeat.labels" . | indent 4 }}
spec:
  selector:
    matchLabels:
      {{- include "metricbeat.labels" . | indent 6 }}
  template:
    metadata:
      labels:
        {{- include "metricbeat.labels" . | indent 8 }}
    spec:
      serviceAccountName: metricbeat
      terminationGracePeriodSeconds: 30
      hostNetwork: true
      dnsPolicy: ClusterFirstWithHostNet
      containers:
        - name: metricbeat
          image: {{ .Values.Metricbeat.image }}
          imagePullPolicy: {{ .Values.imagePullPolicy }}
          args: [ '-c', '/etc/metricbeat.yml', '-e', '-system.hostfs=/hostfs' ]
          env:
            - name: NODE_NAME
              valueFrom:
                fieldRef:
                  fieldPath: spec.nodeName
          securityContext:
            runAsUser: 0
          resources:
            limits:
              cpu: {{ .Values.Metricbeat.resources.limits.cpu }}
              memory: {{ .Values.Metricbeat.resources.limits.memory }}
            requests:
              cpu: {{ .Values.Metricbeat.resources.requests.cpu }}
              memory: {{ .Values.Metricbeat.resources.requests.memory }}
          volumeMounts:
            - name: config
              mountPath: /etc/metricbeat.yml
              readOnly: true
              subPath: metricbeat.yml
            - name: metricbeat-data
              mountPath: /usr/share/metricbeat/data
            - name: proc
              mountPath: /hostfs/proc
              readOnly: true
            - name: cgroup
              mountPath: /hostfs/sys/fs/cgroup
              readOnly: true
      volumes:
        - name: proc
          hostPath:
            path: /proc
        - name: cgroup
          hostPath:
            path: /sys/fs/cgroup
        - name: config
          configMap:
            defaultMode: 0640
            name: metricbeat-config
        - name: metricbeat-data
          hostPath:
            path: /var/lib/logging-system/metricbeat-monitoring/metricbeat-data
            type: DirectoryOrCreate
{{- end -}}