---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Release.Name }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "filebeat.labels" . | indent 4 }}

{{ if .Values.Metricbeat.enabled }}
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: metricbeat
  namespace: {{ .Release.namespace }}
  labels:
    {{- include "metricbeat.labels" . | indent 4 }}
{{- end -}}